# Generated by Django 5.2.8 on 2025-11-18 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Matricula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "periodo",
                    models.CharField(help_text="Ex: 2024.2, 2025.1", max_length=20),
                ),
                ("ativa", models.BooleanField(default=True)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                ("atualizada_em", models.DateTimeField(auto_now=True)),
                (
                    "discente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matriculas",
                        to="core.discente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matrícula",
                "verbose_name_plural": "Matrículas",
                "ordering": ["-criada_em"],
            },
        ),
        migrations.CreateModel(
            name="ReservaLivro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reservada_em", models.DateTimeField(auto_now_add=True)),
                ("ativa", models.BooleanField(default=True)),
                (
                    "discente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas_livros",
                        to="core.discente",
                    ),
                ),
                (
                    "livro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to="core.livro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva de Livro",
                "verbose_name_plural": "Reservas de Livros",
                "ordering": ["-reservada_em"],
            },
        ),
        migrations.CreateModel(
            name="MatriculaDisciplina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adicionada_em", models.DateTimeField(auto_now_add=True)),
                ("ativa", models.BooleanField(default=True)),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matriculas_disciplina",
                        to="core.disciplina",
                    ),
                ),
                (
                    "matricula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disciplinas_matricula",
                        to="core.matricula",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disciplina da Matrícula",
                "verbose_name_plural": "Disciplinas das Matrículas",
                "ordering": ["-adicionada_em"],
                "unique_together": {("matricula", "disciplina")},
            },
        ),
    ]
