# Generated by Django 5.2.8 on 2025-11-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_matricula_reservalivro_matriculadisciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='periodo',
            field=models.CharField(max_length=20),
        ),
    ]
